services:
  jellyfin:
    build:
      context: ..
      dockerfile: local-testing/Dockerfile
    container_name: jellyfin-youtube-plugin-local
    ports:
      - "8096:8096"
    restart: unless-stopped
    volumes:
      - ../.local/jellyfin/config:/config
      - ../.local/jellyfin/cache:/cache
      - ../.local/jellyfin/media:/media
      - ../.local/jellyfin/plugins:/config/plugins