using System.Net.Mime;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Jellyfin.Plugin.YouTubeSync.Controllers;

/// <summary>
/// HTTP API controller that resolves a YouTube video ID to a direct playback URL
/// and returns an HTTP 302 redirect for playback.
///
/// Endpoint: GET /YouTubeSync/resolve/{videoId}
///
/// The .strm files generated by <see cref="SyncService"/> point to this endpoint.
/// When a Jellyfin client initiates playback, it fetches this URL, which in turn
/// calls yt-dlp to obtain the final playback URL and redirects to it.
/// </summary>
[ApiController]
[Route("YouTubeSync")]
[Produces(MediaTypeNames.Application.Json)]
public class YouTubeSyncController : ControllerBase
{
    private readonly ResolveService _resolveService;
    private readonly YtDlpService _ytDlpService;
    private readonly ILogger<YouTubeSyncController> _logger;

    /// <summary>Initializes a new instance of the <see cref="YouTubeSyncController"/> class.</summary>
    public YouTubeSyncController(
        ResolveService resolveService,
        YtDlpService ytDlpService,
        ILogger<YouTubeSyncController> logger)
    {
        _resolveService = resolveService;
        _ytDlpService = ytDlpService;
        _logger = logger;
    }

    /// <summary>
    /// Resolves a YouTube video ID to a direct playback URL and returns an HTTP 302 redirect.
    /// Returns 503 when no compatible playback format is available.
    /// </summary>
    /// <param name="videoId">The YouTube video ID (e.g. dQw4w9WgXcQ).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>302 redirect or 503 if no compatible format is found.</returns>
    [HttpGet("resolve/{videoId}")]
    [ProducesResponseType(StatusCodes.Status302Found)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public async Task<IActionResult> ResolveVideo(string videoId, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(videoId) || videoId.Length > 32)
        {
            return BadRequest("Invalid video ID.");
        }

        _logger.LogInformation("Resolve request for video {VideoId}", videoId);

        var url = await _resolveService.ResolveAsync(videoId, cancellationToken).ConfigureAwait(false);
        if (string.IsNullOrWhiteSpace(url))
        {
            _logger.LogWarning(
                "No compatible playback format available for {VideoId}. Returning 503.",
                videoId);
            return StatusCode(
                StatusCodes.Status503ServiceUnavailable,
                $"No compatible playback URL found for video '{videoId}'.");
        }

        return Redirect(url);
    }

    /// <summary>
    /// Fetches metadata (title, description, thumbnail URL, type) for a YouTube channel or playlist URL.
    /// Called by the admin configuration UI to auto-populate source details.
    /// </summary>
    /// <param name="url">The YouTube channel or playlist URL.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>A <see cref="SourceInfo"/> object, or 400/503 on error.</returns>
    [HttpGet("source-info")]
    [ProducesResponseType(typeof(SourceInfo), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status503ServiceUnavailable)]
    public async Task<IActionResult> GetSourceInfo([FromQuery] string url, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(url))
        {
            return BadRequest("url query parameter is required.");
        }

        _logger.LogInformation("Source-info request for URL {Url}", url);

        var info = await _ytDlpService.GetSourceInfoAsync(url, cancellationToken).ConfigureAwait(false);
        if (info is null)
        {
            return StatusCode(
                StatusCodes.Status503ServiceUnavailable,
                "Failed to fetch source info from YouTube. Check that yt-dlp is installed and the URL is valid.");
        }

        return Ok(info);
    }
}

